## Indexing, Selecting, & Assigning

In [1]:
import pandas as pd

In [4]:
phase_review = pd.read_csv("/home/ankit/Desktop/IITH/SEM_05/Learning-Pandas/phase_review.csv")

# pd.set_option('display.max_rows', 5)

In [5]:
phase_review

,username,email,Name,password
0,cs22btech11022,cs22btech11022@iith.ac.in,GADEKAR SHIVENDRARAJE BABAN,MwLDtUiksy
1,cs22btech11042,cs22btech11042@iith.ac.in,NALAVOLU CHETANA,cUKZvWSkgA
...,...,...,...,...
91,em25mtech14006,em25mtech14006@iith.ac.in,ABHIRAM,6GLWiK13e7
92,em25mtech14009,em25mtech14009@iith.ac.in,MADIHA AHMED,1aVdA3URjH

#### Selecting a specific series out of a DataFrame

In [ ]:
# way 01  (Dot Notation)
phase_review.Name

0     GADEKAR SHIVENDRARAJE BABAN
1                NALAVOLU CHETANA
                 ...
91                        ABHIRAM
92                   MADIHA AHMED
Name: Name, Length: 93, dtype: object

In [ ]:
#Way02  (Square bracket notation)
phase_review['Name']

0     GADEKAR SHIVENDRARAJE BABAN
1                NALAVOLU CHETANA
                 ...
91                        ABHIRAM
92                   MADIHA AHMED
Name: Name, Length: 93, dtype: object

* if there is  a space in the name of the column name then Square Notation is considered valid.
* Dot Notation will not work when there is a space in the name of a column name.

In [12]:
# Column name	    Dot notation	                   Square brackets
# country	        reviews.country ✅	             reviews["country"] ✅
# country province	Not valid ❌	                    reviews["country province"] ✅
# total-score	    Not valid ❌	                    reviews["total-score"] ✅
# mean	            May access a method instead ⚠️	    reviews["mean"] ✅

In [13]:
#Square brackets are more reliable.

In [11]:
# to drill down to a single specific value
# use one indexing operator once more
print(phase_review.Name[2])

print(phase_review['Name'][2])

SIDDHANT GODBOLE
SIDDHANT GODBOLE

#### Indexing in Pandas

##### Indexing based selection
    * Selecting data based on its numerical position in the data.
    * returns a row of the table
    * df.iloc[row_position, column_position]
    * ":" means everything in python

In [19]:
phase_review.iloc[92]

username               em25mtech14009
email       em25mtech14009@iith.ac.in
Name                     MADIHA AHMED
password                   1aVdA3URjH
Name: 92, dtype: object

In [ ]:
print(phase_review.iloc[92, 3])  # row first, then column

print(phase_review['password'].iloc[92])  # first select password column then second its value

1aVdA3URjH
1aVdA3URjH

In [24]:
# get complete column no. 3
phase_review.iloc[:, 3]

0     MwLDtUiksy
1     cUKZvWSkgA
         ...
91    6GLWiK13e7
92    1aVdA3URjH
Name: password, Length: 93, dtype: object

In [ ]:
phase_review.iloc[90]

username               em25mtech11008
email       em25mtech11008@iith.ac.in
Name        VEKARIYA PARTH KISHORBHAI
password                   BvcuAzQrB8
Name: 90, dtype: object

In [38]:
print(phase_review.iloc[-1:-6:-1]) # slicing concept also workingn

print(phase_review.iloc[-5:])

          username                      email                       Name  \
92  em25mtech14009  em25mtech14009@iith.ac.in               MADIHA AHMED
91  em25mtech14006  em25mtech14006@iith.ac.in                    ABHIRAM
90  em25mtech11008  em25mtech11008@iith.ac.in  VEKARIYA PARTH KISHORBHAI
89  em25mtech11007  em25mtech11007@iith.ac.in               ABHAY PANDEY
88  em25mtech11006  em25mtech11006@iith.ac.in         Shrey Pratap Singh

      password
92  1aVdA3URjH
91  6GLWiK13e7
90  BvcuAzQrB8
89  cYiOWPLbZu
88  HZhu4zBvwc
          username                      email                       Name  \
88  em25mtech11006  em25mtech11006@iith.ac.in         Shrey Pratap Singh
89  em25mtech11007  em25mtech11007@iith.ac.in               ABHAY PANDEY
90  em25mtech11008  em25mtech11008@iith.ac.in  VEKARIYA PARTH KISHORBHAI
91  em25mtech14006  em25mtech14006@iith.ac.in                    ABHIRAM
92  em25mtech14009  em25mtech14009@iith.ac.in               MADIHA AHMED

      password
88  HZhu4zBvwc
89  cYiOWPLbZu
90  BvcuAzQrB8
91  6GLWiK13e7
92  1aVdA3URjH

In [39]:
phase_review.iloc[1:3, 0]

1    cs22btech11042
2    cs22btech11054
Name: username, dtype: object

In [42]:
phase_review.iloc[:, 0]

0     cs22btech11022
1     cs22btech11042
           ...
91    em25mtech14006
92    em25mtech14009
Name: username, Length: 93, dtype: object

In [43]:
phase_review.iloc[0:3, 0:3]

         username                      email                         Name
0  cs22btech11022  cs22btech11022@iith.ac.in  GADEKAR SHIVENDRARAJE BABAN
1  cs22btech11042  cs22btech11042@iith.ac.in             NALAVOLU CHETANA
2  cs22btech11054  cs22btech11054@iith.ac.in             SIDDHANT GODBOLE

In [44]:
# we can pass a list also

phase_review.iloc[[0,1,2], [0,1,2]]

         username                      email                         Name
0  cs22btech11022  cs22btech11022@iith.ac.in  GADEKAR SHIVENDRARAJE BABAN
1  cs22btech11042  cs22btech11042@iith.ac.in             NALAVOLU CHETANA
2  cs22btech11054  cs22btech11054@iith.ac.in             SIDDHANT GODBOLE

In [45]:
# A Range of rows can be selected
# A Range of cols can be selected
# Can be selected using either ":" or "list".

##### Label based indexing
    * its data index value, not its position, which matters.
    * df.loc[row_label, column_label]
    * when column names are meaningful, its easier to do things with loc instead.

In [29]:
phase_review.loc[2, 'password']

'sP284Hegtg'

In [32]:
# giving all rows for 2 selected columns
phase_review.loc[:, ['password', 'Name']]

      password                         Name
0   MwLDtUiksy  GADEKAR SHIVENDRARAJE BABAN
1   cUKZvWSkgA             NALAVOLU CHETANA
..         ...                          ...
91  6GLWiK13e7                      ABHIRAM
92  1aVdA3URjH                 MADIHA AHMED

[93 rows x 2 columns]

##### iloc vs loc

In [46]:
# in given range 0:10
    # iloc chooses 0 to 9
    # loc chooses 0 to 10

In [48]:
df = pd.DataFrame({
    "Price": [100, 60, 80, 120]
}, index=["Apples", "Bananas", "Oranges", "Potatoes"])


df.loc["Apples":"Oranges"]


#This is convenient because you can specify the actual ending label.

df.iloc[:3]

         Price
Apples     100
Bananas     60
Oranges     80

In [49]:
df.iloc[:3]

         Price
Apples     100
Bananas     60
Oranges     80